export {default as AboutMe} from './AboutMe'
export {default as Contact} from './Contact'
export {default as Container} from './Container'
export {default as ProjectCard} from './ProjectCard'
export {default as TechStats} from './TechStats'
export {default as Home } from './Home'
export {default as Project} from './Project'