export {default as AboutMe} from './about-me/AboutMe'
export {default as Contact} from './contact/Contact'
export {default as Container} from './Container'
export {default as ProjectCard} from './project/ProjectCard'
export {default as TechStats} from './about-me/TechStats'
export {default as Home } from './Home'
export {default as Project} from './project/Project'